name: Cleanup Artifacts

on:
  schedule:
    - cron: '0 13 */8 * *'  # Cada 8 días a las 8:00 AM Colombia (13:00 UTC)
  workflow_dispatch:

permissions:
  actions: write  # Necesario para borrar artefactos

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than 8 days
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '8 days'
